#!/bin/bash
if 	test `kreadconfig5 --file $HOME/.config/kioslaverc --group "Proxy Settings" --key "ProxyType"` -eq 1
then
	kwriteconfig5 --file $HOME/.config/kioslaverc --group "Proxy Settings" --key "ProxyType" 0
else
	kwriteconfig5 --file $HOME/.config/kioslaverc --group "Proxy Settings" --key "ProxyType" 1
fi
